### ISSUE TITLE
API fails when network connection is interrupted

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring-alarm#15]
I'm back.  I tried to use the onConnected observable and it works to provide notification when the websocket is disconnected, however, almost immediately I get an unhandled promise warning.  Also, if I remove the Internet block, it does not reestablish the connections automatically and I can't figure out any way to make it reconnect from within my code.  I do not have this reconnect issue with the ring-api code.  This could still easily be something I'm doing incorrectly, but I get the error even with the example code.

If it helps, below is the output from a slightly modified version (my platform is Node 8.x so I couldn't seem to use import) of the example script after I interrupt the internet connections with a firewall rule:

**** Disconnected from alarm at location a234428cb-cbfc-761c-4598-29d23f33dcd8
Request to https://app.ring.com/api/v1/rs/connections failed
(node:451) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 54.85.88.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
(node:451) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:451) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dgreif** [comment]
@tsightler Thanks for testing it out! I was only checking for `ENOTFOUND`, which apparently didn't catch the error from your firewall exception.  I've updated the failure check to look for any network error, so it should definitely catch your `ETIMEDOUT`.  Give `1.2.3` a try.

**Comment by tsightler** [comment]
Tested and it works great with all disconnect events I'm able to simulate.  Exactly what I was looking for, now I can indicate connectivity status of the various alarms and, just as importantly, rescan state and device changes when reconnects happen as sometimes they seem to get lost.  Thanks so much!

**Comment by dgreif** [comment]
@tsightler glad it's working for you now! Thanks for spurring me forward.  I needed a good excuse to extract everything from `ring-api` since it doesn't seem to be maintained anymore.
