### ISSUE TITLE
User/password printed to console

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring-alarm#16]
Perhaps you don't consider this a bug, but there's a console log of the username/password in clear text whenever you make a connection to the alarm.  I use debug for most of my scripts and, normally, they produce no console output otherwise, so this just struck me as odd.  I ended up looking for a leftover console.log statement in my code that I somehow didn't remember before I realized it was coming from the API code.

**Comment by dgreif** [comment]
Yep, that was definitely a mistake on my part.  Logging was the one piece that I hadn't set up yet since pulling everything out of `ring-api`.  `debug` seems like the way to go, so I got it set up in `1.2.4` under `DEBUG=ring-alarm`.  Thanks for the suggestion!
