### ISSUE TITLE
Multiple Homes in a single account

### ISSUE THREAD

**Issue by SafariKC** [dgreif/ring-alarm#17]
It would be fantastic if you would allow a configuration to be set to allow for only pulling in the devices for a single location.  our ring account has multiple locations and it would be nice to have a home bridge config to be separate for each of them as they are separate homes.

**Comment by dgreif** [comment]
I think that's a reasonable request. Should be pretty straightforward to add an optional location id array to the config.  I'll take a look when I get a chance.

**Comment by dgreif** [comment]
@SafariKC I've added a `locationIds` option to the config.  Let me know if that solves your issue.  Thanks for the feature request, hopefully it will be useful for others as well.

**Comment by SafariKC** [comment]
Thanks so much!  I’ll give it a whirl.

**Comment by SafariKC** [comment]
@dgreif Can you add some default logging that shows the LocationID's that are found on the account.  I'm hunting through logs right now in debug mode but i'm not entirely clear what if any logging is telling me the location right now via homebridge.

**Comment by SafariKC** [comment]
I was able to get it myself with a web inspector via their portal.  But it would be nice to log that if you have it already.

**Comment by SafariKC** [comment]
Also for someone who set this up before there was a restriction in place, it looks like it's using the cached configs even if the locationIds would have restricted them out.  I've blown away my homebridge cache and things are working great but it might be nice if it invalidated these as well when a restriction is in play.

**Comment by dgreif** [comment]
@SafariKC I think you are spot on with all of your suggestions.  Just released `v1.4.1` which has location id logging, and will automatically prune any devices that are from filtered out locations.  Thanks for the great ideas!
