### ISSUE TITLE
Random Mode Changes

### ISSUE THREAD

**Issue by VeniceNerd** [dgreif/ring-alarm#18]
Hey,

I’ve been noticing random mode changes for the past few weeks. All of the activity in the screenshot was happening while I was asleep:

![dfdc71f3-9c23-43a1-9c09-9bf8a21ceccb](https://user-images.githubusercontent.com/25128243/53304147-0c22d480-3827-11e9-964d-99f30610ef94.png)

Is it possible that this plugin may have something to do with that? How can I find out?

Thanks!

**Comment by dgreif** [comment]
@VeniceNerd That seems pretty odd.  It's possible that you have an automation of some sort in HomeKit triggering the changes.  It's interesting that all of the notifications are changes to "Disarmed", but no other state (might just be your notification preferences).

As for debugging whether or not it is the homebridge plugin, I added some logging in `v1.4.1` that will tell you when HomeKit sets the alarm mode.  Give that a try and see if it is indeed coming from the plugin side.

**Comment by dgreif** [comment]
@VeniceNerd any updates?

**Comment by VeniceNerd** [comment]
This hasn’t happened again since. So I’m gonna just close this thread and make a new one should this ever occur again!
