### ISSUE TITLE
Ring is blocking me?

### ISSUE THREAD

**Issue by talshum** [dgreif/ring-alarm#21]
I suspect that every time I try to use the script RIng is blocking me. After launching it I'm unable to access my ring account from my phone or online. This time I got:

" error Couldn't create the API instance. This could be because ring.com changed their API again"

**Comment by dgreif** [comment]
@talshum I haven't had any issues with getting logged in.  That error doesn't exist in the codebase so I'm guessing you are a few versions behind.  Try updating to the latest version and double checking your password.  Let me know if that works!

**Comment by dgreif** [comment]
@talshum any updates on this issue?

**Comment by talshum** [comment]
Now it’s working. Was coincidence


________________________________

**Comment by dgreif** [comment]
Great, glad to hear that.  Thanks!
