### ISSUE TITLE
Support for ring two step verification?

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring-alarm#26]
is it even possible to support ring's two step verification?

**Comment by dgreif** [comment]
I'm guessing it would be _possible_ if we took an approach like https://github.com/KhaosT/homebridge-nest-cam#how-to-get-access-token.  The main issue is that you need to be in the loop every time a new token is required by the plugin.  There should be a token refresh endpoint, but if your homebridge was offline for a day or more, your token would probably expire and require you to update your configuration file with a new manually fetched token. I'm all for 2fa, so i'd be happy to review a PR if someone has time to work on this.
