### ISSUE TITLE
Smart Light Group or Light Hiding Option?

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring-alarm#27]
Is there anyway that you can put an option into this plugin so that you can make it so that the "Patio Group" Light doesn't show or is hidden? because then if we want to group our lights together we can with HomeKit.

![IMG_E081330F784D-1](https://user-images.githubusercontent.com/9875439/58264675-d9b04700-7d43-11e9-896c-b56168b220a5.jpeg)
![IMG_67BEA2C94167-1](https://user-images.githubusercontent.com/9875439/58264774-10865d00-7d44-11e9-86db-2350675e2954.jpeg)

**Comment by evisser4** [comment]
I'd like this as well.  Good idea.

**Comment by dgreif** [comment]
The easiest path would probably be to just delete the group within HomeKit after it gets registered by homebridge.  I don't think it will re-appear unless you clear your homebridge cache.

That aside, I'm happy to add a config option.  Are you thinking something as simple as `hideLightGroups: true`, or more complex like `hideDeviceZids: ['123abc', '456def']`?

**Comment by d0n4v4nb3ck3r** [comment]
>~~The easiest path would probably be to just delete the group within HomeKit after it gets registered by homebridge.  I don't think it will re-appear unless you clear your homebridge cache.~~ Apparently you cannot remove individual devices if they are added from a bridge 😞  ...

@dgreif I would like the individual devices to be seen, but not the group. If that’s possible. If you want me to test each one of those and let you know, I can do that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
Released `v2.1.0` with a `hideLightGroups: true` option.  Should automatically remove those group lights/sensors from HomeKit, so no need to clear homebridge cache.

**Comment by d0n4v4nb3ck3r** [comment]
Thank you so much for doing this!
