### ISSUE TITLE
beamdurationseconds

### ISSUE THREAD

**Issue by evisser4** [dgreif/ring-alarm#28]
The light doesn't turn on with beamdurationseconds over 32500.

**Comment by dgreif** [comment]
Thanks for the info! I didn't test the upper bounds, but that's right at 9 hours.  Seems like a pretty smart maximum since the most of the lights are battery powered.  I'll add some information to the readme.  Anything else you think we should do?

**Comment by dgreif** [comment]
Added it to the readme and put a check in place.  Now if you set the value too high, it will use the max allowed value (`32767`).  Thanks for bringing the issue to my attention!

**Comment by evisser4** [comment]
Thank you! Is it possible to disable this timeout altogether? I have a wired smart light that I want turned on at sunset and turned off at sunrise. 9 hours doesn't quite cut it in my scenario.

**Comment by dgreif** [comment]
Unfortunately that limit is coming from Ring, not from anything on my end.  If 9 hours isn't quite enough, you could probably add a second automation that would run in the middle of the night.  So at sunset, turn on the light for 9 hours.  Then at 1am turn it on for 9 hours again (which would basically just reset the duration timer).  Then at sun rise turn it off.

**Comment by evisser4** [comment]
Thanks a lot! Your solution worked perfectly.
