### ISSUE TITLE
Crashes when Ring Alarm is on backup Cellular

### ISSUE THREAD

**Issue by eddydas** [dgreif/ring-alarm#29]
Plugin crashes upon homebridge start up with "Cannot find 'reduce' in undefined" when the Ring Alarm is on Cellular network.

"deviceList" can be undefined in location.js

**Comment by eddydas** [comment]
My internet is spotty, so from time to time my Ring Alarm would go into Cellular mode for some time :(

**Comment by dgreif** [comment]
Updated in `v2.2.1`.  It will now wait until the base station is online before it tries to do anything in homebridge.
