### ISSUE TITLE
Error when running home bridge-ring-alarm@3.0.0 for the first time

### ISSUE THREAD

**Issue by LeviJSmith** [dgreif/ring-alarm#31]
I am getting the following error trying to run the plugin.  
![Screen Shot 2019-06-16 at 11 08 20 AM](https://user-images.githubusercontent.com/51886586/59567262-adc57000-9028-11e9-8d2d-bb3cc73124ad.png)

**Comment by dgreif** [comment]
Make sure you have it configured under `platforms` and not `accessories` in your homebridge config.  See https://github.com/dgreif/ring-alarm/tree/master/homebridge#homebridge-configuration for an example.  If that isn't the issue, can you post what version of homebridge and node you have installed?

**Comment by LeviJSmith** [comment]
Greetings.  Thanks for thew quick response.  I confirmed I have it installed under platforms.  Below is my Node and Homebridge versions.

Node V9.8.0

Homebridge 0.4.38

Thanks,
Levi

**Comment by dgreif** [comment]
I would try updating homebridge. Looks like 0.4.50 is the latest

**Comment by LeviJSmith** [comment]
Ok, thx.  Will give that a try.  Have a good evening!!

-Levi

**Comment by LeviJSmith** [comment]
Updating to 0.4.50 did the trick.  Thx for your help.
