### ISSUE TITLE
Using Siri

### ISSUE THREAD

**Issue by cantchooseaname8** [dgreif/ring-alarm#36]
This isn’t really an issue but wanted to get your input more than anything. I used to be able to tell Siri “Turn Ring Alarm off” to deactivate the alarm. When I say it now, it activates the new siren switch. Do you have any suggestions for what commands I could say for Siri to control the alarm to turn it off?

**Comment by ifeign** [comment]
You could create a scene with that name and have it turn off the alarm.

**Comment by cantchooseaname8** [comment]
@ifeign that’s exactly how I have it set up. I have a scene called “Ring Alarm Off” but it now triggers the siren switch. I’ll keep testing out alternatives but if anyone has any suggestions, I’m all ears.

**Comment by smockle** [comment]
@cantchooseaname8 I think the scene should be called “Ring Alarm”, not “Ring Alarm Off”. If the scene is called “Ring Alarm”, Siri should interpret the phrase “Turn Ring Alarm off” as “Turn [scene] Ring Alarm [to the] off [state]” (i.e. disable it).

**Comment by cantchooseaname8** [comment]
@smockle I don’t think scenes can toggle a device back and forth between on and off. When setting up a scene you have to select a specific state for the device. In this case my scene has the alarm set to the specific state of being off. So when I say “Ring Alarm Off” it should run that specific scene which sets the alarm to off. However it doesn’t work anymore. It works fine when I manually press the button for the scene but not when I say it. Maybe Siri just hasn’t evolved enough to take on the settings of alarm systems yet.

**Comment by dgreif** [comment]
@cantchooseaname8 take a look at https://github.com/dgreif/ring-alarm/tree/master/homebridge#changes-modes-on-arriveleave-home if you haven't already.  If you go though the work of setting it up, you never have to think about arming/disarming your alarm when you come and go.  As for arming at night, you could create other names for the scenes like "Good Morning"  and "Good Night" or whatever makes sense for you to arm for "Home" at night and to turn it "Off" in the morning. Hope that helps!

**Comment by cantchooseaname8** [comment]
@dgreif I have that set up to automatically arm whenever we leave the geofence by using the dummy switches and it works great. Never have to worry about it (unless we accidentally leave a window open). About a year ago I had a homeless guy jump into my yard at the same time I was getting home so I never set it up to automatically disarm when I get home. That experience made me a little nervous to do that. I also use the shortcuts app to automatically set it to Home mode at night and deactivate it in the morning. I'm just looking for a way to deactivate it via Siri right before I open my doors when coming home. I'll just keep tinkering with it and may need to create some new scenes and names. There might just be some overlap in my scenes and device names which confuses Siri.

**Comment by dgreif** [comment]
@cantchooseaname8 that is a really scary scenario that has gone through my mind once or twice, but I never thought it would happen!  Makes sense that you would be a little cautious after going through that.  Hopefully you can come up with a scene name that makes sense and get it working again.  Mind if I close this issue since it's not directly related to the plugin?

**Comment by davidn70** [comment]
I recently "discovered" the new siren switch by accident like this myself.  I have it working the "old" way with Siri again by renaming the siren switch and put it in a different room in the home app from the rest of my ring alarm components.  I can now tell Siri to turn the ring alarm off and on and it works like it used to.  Hope this helps - YMMV.

**Comment by cantchooseaname8** [comment]
@dgreif yeah please go ahead and close it out. Thanks for all the help. 

@davidn70 thanks for the tips. I’ll try renaming it and moving it to a different room.

**Comment by dgreif** [comment]
@cantchooseaname8 I had another person asking about Siri commands so I looked into it more.  I've added a list of functional commands to the readme: https://github.com/dgreif/ring-alarm/tree/master/homebridge#siri-commands-for-alarm.  I also an option to get rid of the siren switch entirely (`hideAlarmSirenSwitch`) if you liked the old way better.

**Comment by cantchooseaname8** [comment]
@dgreif I just updated to 3.7.1 and added the hideAlarmSirenSwitch to my config.json file. I followed that by rebooting homebridge. However, the siren switch is still in HomeKit. It didn't get removed for some reason. Any idea what might be causing this?

**Comment by dgreif** [comment]
@cantchooseaname8 I noticed some oddities with this when I implemented it.  I think I just tracked down the issue.  Give v`3.8.1` a try

**Comment by cantchooseaname8** [comment]
@dgreif that did the trick. Thank you!
