### ISSUE TITLE
camera shown only on one device

### ISSUE THREAD

**Issue by divemasterjm** [dgreif/ring-alarm#41]
Hi, ive come with another issue, i only have the camera on the first device ive added, if i open home app on other devices (ipad or macbook) i cant find the camera/door sensor ive got on iphone. Also the sensor is not firing up only sometimes.

**Comment by dgreif** [comment]
@divemasterjm Sorry to hear you are having more issues.  The "external" devices in homebridge can apparently get into a funky state.  First, make sure you only have the ring plugin running in a single instance of homebridge, and make sure you don't have any other ring camera plugins (like homebridge-platform-ring-video-doorbell) running, as these can mess with notification reliability.  Assuming that is all good, your best bet is to strip out the existing cameras from your homebridge config and re-add them.  Here are the steps for cleanup:

* Stop homebridge
* Go into your `~/.homebridge/persist` directory and finding any `AccessoryInfo.${uniqueId}.json` files that relate to your camera.  You can open them up and they have the device name right at the start of the file.  Keep track of the `${uniqueId}` values for your cameras. Delete each camera's `AccessoryInfo.${uniqueId}.json` and associated `IdentifierCache.${uniqueId}.json` file
* Remove the cameras from HomeKit via the Home app
* Start homebridge
* Re-add the cameras like you did the first time around

Hopefully that gets you straightened out.  Let me know if you run into any other issues or if this doesn't resolve the problem

**Comment by divemasterjm** [comment]
i tried everything you told me, still doesnt work, have you think to put also the ring sensor?

**Comment by dgreif** [comment]
By `ring sensor`, do you mean a sensor that gets triggered when you press the doorbell? If so, it is already present.  HomeKit hides it behind the scenes as part of the camera, but it should still trigger notifications when the doorbell is pressed.  Do you want to see it as a separate sensor like it was in `homebridge-platform-ring-video-doorbell`?

**Comment by divemasterjm** [comment]
yes is very useful if you want to do any actions when triggered, like play sound trouhgt homepod, ive been investigating a bit, the prroblem of camera on others is ios 13 beta.

**Comment by dgreif** [comment]
Ahh, great to know you tracked that issue down!  I haven't tried ios 13 beta yet, but I'll hold off now that I know it's causing issues.  Thanks for letting me know!

As for the sensor switch, I'll look into getting it added.

**Comment by dgreif** [comment]
@divemasterjm I've added a `StatelessProgrammableSwitch` in v`3.3.0`.  You can add actions to the `Single Press` event.  _Notifications_ for doorbell presses are handled separately, as part of the main camera feed settings

**Comment by d0n4v4nb3ck3r** [comment]
> @divemasterjm I've added a `StatelessProgrammableSwitch` in v`3.3.0`. You can add actions to the `Single Press` event. _Notifications_ for doorbell presses are handled separately, as part of the main camera feed settings

pretty cool that you added this. Anyway to make it an option in parameters so that if people don't want it they can disable it?

**Comment by divemasterjm** [comment]
Thanks, I will give a try, if you some beta test just tell me. I’ve got appletv 4 and iPad running iOS 13 and HomePod, iPad Pro, MacBook and iPhone XS Max on Las iOS 12.

**Comment by divemasterjm** [comment]
Hi, after trying 3.3.0 i have no snapshot image on camera anymore

**Comment by divemasterjm** [comment]
After disabling iOS 13, still have problems on others devices only on the one I’ve added camera

**Comment by dgreif** [comment]
@divemasterjm sorry to hear you are still having issues.  I would recommend going through the remove/add process again that I detailed before.  Probably something weird in HomeKit on ios 13 beta

**Comment by divemasterjm** [comment]
After 24h of sync, now is working except sensor which is in another thread, thanks for your support.

**Comment by briangot2** [comment]
I still cannot get the ring camera screenshot to show up on a second device (invited user via homekit). I am on the latest version of your module and I followed your instructions above by deleting the files and re-adding the camera. I just can’t get it to show the camera screenshot on my wife’s phone. Any help would be appreciated.

**Comment by dgreif** [comment]
@briangot2 See #45.  Do you have a doorbell_v3? (Check the `Model` section in the camera settings in the Home app)

**Comment by briangot2** [comment]
Yes. doorbell_v3
