### ISSUE TITLE
Add battery life to Doorbells

### ISSUE THREAD

**Issue by ifeign** [dgreif/ring-alarm#43]
I noticed that though in your readme it says that your plugin supports camera battery life, it is not reported for cameras. It works in this plugin https://github.com/homespun/homebridge-platform-ring-video-doorbell

**Comment by dgreif** [comment]
@ifeign I do have the low battery alerts set up, but not the actual battery level.  My cameras are all wired so I don't have a good way to test it out, but I can push an update in the next few days that takes a stab at battery levels.  I'll let you know when it's out

**Comment by ifeign** [comment]
Wonderful. I am grateful that you are so actively developing this plugin!
I'll be happy to test your battery implementation since you don't have
anything battery powered.

**Comment by dgreif** [comment]
@ifeign added in v`3.5.0`.  Should show up if the device is < 100%, and then will show from then on.  Wired cameras always report 100%, so I have to see < 100% to know it's battery powered 😕.  Let me know how it works for you!

**Comment by ifeign** [comment]
Just tried it out, works great! Thank you so much.

**Comment by dgreif** [comment]
@ifeign thanks for testing out the battery life.  Are there any other features from that other homebridge plugin that I am currently missing?

**Comment by ifeign** [comment]
> @ifeign thanks for testing out the battery life. Are there any other features from that other homebridge plugin that I am currently missing?

Nope! Seems like you have either met or exceeded the functionality of the other plugin.
