### ISSUE TITLE
Customize Doorbell Programable Switch

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring-alarm#46]
Sorry to be so needy, but is there anyway you could add an option to disable the programable switch if someone would prefer not to have it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
@d0n4v4nb3ck3r no problem at all!  I told you I would do it, but it got lost in another issue.  Try `hideDoorbellSwitch: true` in v`3.4.0`

**Comment by d0n4v4nb3ck3r** [comment]
@dgreif
>@d0n4v4nb3ck3r no problem at all!  I told you I would do it, but it got lost in another issue.  Try `hideDoorbellSwitch: true` in v`3.4.0`

@dgreif I am so sorry!! I wasn’t sure if you saw that in one of the other issues or not. And wasn’t sure you responded to me or someone else. Thank you so much for adding this know!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
