### ISSUE TITLE
Question About Homekit

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring-alarm#47]
Hello
Does all acceccories connected to the alarm base station show up in homekit as sensor? Door / Window Sensor / Smoke / Motion Detectors?

**Comment by dgreif** [comment]
@malmentm yes, the homebridge plugin supports all of those and more.  See https://github.com/dgreif/ring-alarm/tree/master/homebridge#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs for the full list.  If you have any z-wave devices connected to the hub that are currently not supported, please let me know and I will get them added.

**Comment by malmentm** [comment]
> @malmentm yes, the homebridge plugin supports all of those and more. See https://github.com/dgreif/ring-alarm/tree/master/homebridge#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs for the full list. If you have any z-wave devices connected to the hub that are currently not supported, please let me know and I will get them added.



> @malmentm yes, the homebridge plugin supports all of those and more. See https://github.com/dgreif/ring-alarm/tree/master/homebridge#supported-devices-via-ring-alarm-and-ring-smart-lighting-hubs for the full list. If you have any z-wave devices connected to the hub that are currently not supported, please let me know and I will get them added.

Hello again. I tried to add a Heiman smoke sensor to the base station. But in HomeKit it shows up as a contact sensor. 

can it be made to show as a smoke sensor instead?

**Comment by dgreif** [comment]
Can you check to see what value HomeKit reports if you go into the settings for that sensor and check the `Model` field?  Should be something like `sensor.contact`.  Also, how does the sensor show up in the Ring app?

If you want to give me full context, follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery

**Comment by malmentm** [comment]
It says only Model:sensor in HomeKit. In ring app it says Binary Sensor 48618

**Comment by dgreif** [comment]
Sounds good.  Unfortunately the `Model: sensor` means that Ring doesn't know what _type_ of sensor it is, so it just gives it a general categorization.  In the plugin, it's easiest to represent these unknown sensor types as a contact sensor, which gives you the option to change to a limited set of sensors in HomeKit (door, window, garage door, etc).  Since Ring doesn't know it's a smoke sensor, the plugin can't know that either.  I think the behavior you see is the best I can do.

**Comment by malmentm** [comment]
Okay thanks :) I also wonder if it might work to pair a z-wave lock to the base station and make it appear in homekit (as a lock) or will I be in the same situation as with the smoke sensor?

**Comment by dgreif** [comment]
As long as Ring registers it as a lock, then the plugin will handle it as a lock in HomeKit.  I have a couple august locks that support z-wave and I know they work perfectly.  The problem is just with the smoke sensor since Ring doesn't know what type of sensor it is.

**Comment by malmentm** [comment]
Ok :) So other brand the those on the “works with ring” list might be compatible anyway? I guess to try is the only way to find out then.

**Comment by malmentm** [comment]
I have connected the Danalock to the Ring hub and it seems to work perfect :)
