### ISSUE TITLE
Doorbell doesn't appear with shared user account

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring-alarm#48]
I have a weird issue that I just can't seem to figure out.  I was trying to add support for cameras to my ring-alarm-mqtt bridge script (probably with a rename to ring-mqtt since it will no longer be just for Ring alarm) but I've hit a snag.  I use a shared user account for all of my integrations for multiple reasons, mainly that I have 2FA enabled on the owner account, but also because my owner account has access to some other locations that are shared with me that I don't really want part of my integrations (yes I know I can limit this with location IDs, I even have that support in my script config, but I find it easier to just create an account with only the items I want as I can be granular even per location).  Not only that, but it's an easy way to control what devices show up in Home Assistant and this way my automation actions are logged with a custom username instead of my name (in my case I created an account named Home Assistant so it's really clear).

Anyway, I've shared all the devices that I want to show up in my integrations with this shared user account.  I only have a single location and I have an alarm and 4 cameras in total, two stickup cams, a floodlight cam, and a doorbell pro.  If I login to the app or use this account with the Home Assistant native plugin, all of these devices appear and work perfectly.  However, when I use this account with the API, I get 3 of the 4 cameras and the alarm, but the Doorbell Pro never shows up regardless of if I use getCameras() or locations.cameras.

However, if I switch to use the owner account, then I'm able to see all four cameras, including the Doorbell Pro, with no issues.  Any ideas around this?  It's just such a strange issue I'm not sure what could cause this?  What can I provide that might help troubleshooting?

**Comment by dgreif** [comment]
@tsightler glad to see you are adding cameras! I have been debating a name change as well for the same reasons.  As for the shared doorbell, I think you stumbled on an area I need some slight improvements.  The `ring_devices` endpoint returns `doorbots`, `stickup_cams` and a third array that I have so far been ignoring called `authorized_doorbots`.  I am guessing the shared doorbells show up in that third array.  I've pushed a change to https://github.com/dgreif/ring-alarm/tree/authorized-doorbots which should add that last camera in for you if my theory is correct.  Would you mind pulling that branch and hacking up the `examples/example.ts` file to test it out?  You can run the example with `npx ts-node ./examples/example.ts`.

If you confirm it works, I'll merge that branch and cut a release.  Thanks for your continued investment in the Ring OSS community 😄

**Comment by tsightler** [comment]
@dgreif you are too fast!  I'll admit I probably spent too much time figuring out how to clone a branch and get compiled Javascript from the Typescript source, but once I got past that it worked perfectly.  Thanks for the quick turnaround.

I've already managed to get crude camera support working, so now I just need to clean that up and work on some of the cooler features, like adding camera snapshot support via MQTT.

**Comment by dgreif** [comment]
@tsightler glad it worked!  Version `3.6.0` released.  Sorry about the typescript stuff, it's great when you are used to it, but definitely extra work if you are used to vanilla js.  I hope your additions for MQTT go well.  I've got snapshots tuned pretty well at this point.  Let me know if you run into any issues or need anything else added to the API.

**Comment by tsightler** [comment]
Ha, no sweat on the typescript stuff, I mostly hack around on this stuff to learn a little about coding so it was a learning experience, it wasn't really that difficult, just got spoiled to the fact that when I do npm from the master branch it "just works".

**Comment by d0n4v4nb3ck3r** [comment]
@tsightler just to make you aware, Ring is enabling sharing access to the ring smart lights. I am not sure if you had issues with that at all with your shared account or not. But got an email back from the head of the ring smart lights department and they enabled it for me already and are enabling everyone else this week he said.

**Comment by tsightler** [comment]
Current code doesn't have any support for smart lights, and I don't own any, so it's mostly irrelevant to me at this point.

I am marginally interested in the path lights, but being battery powered does't get me too excited about them when I can buy much cheaper wired ones and turn them on/off with a $10 wifi switch.
