### ISSUE TITLE
Alarm instructions and stupid SIREN!!!

### ISSUE THREAD

**Issue by jcleek** [dgreif/ring-alarm#49]
I like to think I am a technical guy. For the life of me I cannot consistently arm (home and away) and disarm my Ring. The stupid siren keeps coming on.

1) What are the actual full Siri commands to arm in home, away and disarm?
2) Can teh siren switch be DELETED??

**Comment by dgreif** [comment]
@jcleek sorry to hear you are having issues!  We have had some previous discussion around using Siri in #36.  I can definitely add an option to hide the siren switch if need be.  Just did some testing and it looks like these commands work fine:

`Set Ring Alarm to Away` or `Arm my security system`- Away mode activated
`Set Ring Alarm to Stay` or `Arm my security system for stay`- Home mode activated
`Disarm Ring Alarm` or `Disarm my security system` - Disarmed

`Turn on Ring Alarm` - Turns on siren
`Turn off Ring Alarm` - Turns off siren

PS: Just tried "Turn Ring Alarm On" and damn that is loud/annoying.  Sorry for the frustration!

**Comment by jcleek** [comment]
Adding an option to remove the siren completely would be awesome. I will try the other commands later when I get home and report back. Thanks!

**Comment by dgreif** [comment]
Added a `hideAlarmSirenSwitch` in v`3.7.0`.  Also added Siri commands to the readme: https://github.com/dgreif/ring-alarm/tree/master/homebridge#siri-commands-for-alarm.  Let me know how that works for you

**Comment by jcleek** [comment]
Your commands seem to work perfectly. Thank you! Now about that siren...

**Comment by jcleek** [comment]
BTW I am using ARM MY.... and DISARM MY. Those work.

**Comment by jcleek** [comment]
The siren disable works as well. Thank you!
