### ISSUE TITLE
After 3.6 Update

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring-alarm#51]
Ever since I updated to 3.6 I have not got an update for the snapshots. I am going to do a reset of my HomeBridge to start from scratch and see if that’s what the problem is. If not just wanted to let you know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
Odd...I've been keeping mine up to date and it's working fine.  Let me know how the rest goes.  What model of camera do you have?

**Comment by d0n4v4nb3ck3r** [comment]
I have the ring doorbell pro and the floodlight
