### ISSUE TITLE
isDoorbot flags false for Doorbell Pro

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring-alarm#52]
Looking at your homebridge code it seems that you use isDoorbot to determine if a device is an actual doorbell vs just a camera which is also what I was attempting to do when using the API.  However, this does not seem to be reliable as my Doorbell Pro (kind: lpd_v2) shows "isDoorbot: false" but is obviously a doorbell.  Is there some other way to determine if a device is a doorbell vs just a camera?  I can obviously create a function to check against a list of known device types, but this seems less than ideal from a maintenance perspective.

**Comment by dgreif** [comment]
My bad! I’m guessing that is your camera from the shared account. It’s because it is in authorized doorbots instead of doorbots. I’ll get a fix out when I can, might be a day or two.

**Comment by tsightler** [comment]
Ah, OK, that makes sense now.  It's no rush, I can hack around it for now and I won't have my code ready and tested for release for a few weeks anyway due to other things pulling me away.

**Comment by dgreif** [comment]
@tsightler give v`3.7.2` a shot.  It was definitely an oversight when I added authorized doorbots.  Thanks for letting me know!

**Comment by tsightler** [comment]
It works!  Thanks for the update.

**Comment by dgreif** [comment]
Awesome! Sorry for creating a bug with my shared devices fix lol. Thanks for all your feedback, it’s great to have someone testing more corner cases than I can with my setup.
