### ISSUE TITLE
Add feature to hide motion sensor

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring-alarm#54]
Hello! Would it be possible to add an option to hide the motion sensor in HomeKit?

**Comment by dgreif** [comment]
@malmentm just the camera motion sensors?  The alarm has motion sensors too

**Comment by malmentm** [comment]
The Doorbell Camera. I don't use it so it feel unneccesary to have them shown in homekit 💃

**Comment by dgreif** [comment]
Added `hideCameraMotionSensor` in v`3.8.0`.   Let me know how it works for you.

**Comment by malmentm** [comment]
Worked great! Thanks :)
